// payload.mjs : the authored content of the target walkthrough.
//
// Claims reference the reader dossiers under ./dossiers/ so every quote stays
// verbatim; build.mjs re-resolves each quote to line numbers against the
// snapshot and deletes what fails. Nothing in this file carries a line number.
// House rule: no em or en dashes anywhere in any string.

import { readFileSync } from 'node:fs';

const R = n => JSON.parse(readFileSync(new URL('./dossiers/' + n + '.json', import.meta.url)));
const core = R('core-cli'), dat = R('data'), fea = R('features'), mod = R('models'),
  pev = R('pipeline-eval'), eco = R('econ-gsvivs'), tst = R('tests'),
  aos = R('agent-os'), ops = R('workspace-ops'), cfg = R('configs-experiments');

// claim i of dossier d, optionally overriding the sentence
const C = (d, i, text, extra = {}) => ({
  text: text || d.claims[i].text,
  anchor: { file: d.claims[i].file, quote: d.claims[i].quote, ...extra },
});
const INF = text => ({ text, });                     // inferred: no anchor
const A = (d, i, extra = {}) => ({ file: d.claims[i].file, quote: d.claims[i].quote, ...extra });

const ENV = 'captured 2026-07-30, Windows 10, Python 3.12.8, pytest 9.1.1';

// ---------------------------------------------------------------- glossary
const glossary = [
  { id: 'qlike', term: 'QLIKE', def: 'The quasi-likelihood loss for variance forecasts, mean(RV/h - log(RV/h) - 1), equivalently exp(e) - e - 1 on the log-space error e. It punishes under-predicting volatility more than over-predicting it, which matches the economics: being short of realized vol is the expensive mistake. Every trainable model here optimizes it directly and the tournament ranks by it.', anchorSrc: A(pev, 0) },
  { id: 'rv', term: 'realized variance', def: 'The sum of squared intraday returns over one trading day, computed from 5 minute returns with no mean subtraction. It is the quantity every model in this repo forecasts.', anchorSrc: A(dat, 0) },
  { id: 'har', term: 'HAR', def: 'The heterogeneous autoregressive model: regress tomorrow\'s log RV on the daily value, the 5 day mean, and the 22 day mean of past RV. Three parameters, brutally hard to beat, and the baseline every ML model in the tournament is scored against.', anchorSrc: A(fea, 2) },
  { id: 'bpv', term: 'bipower variation', def: 'A jump-robust estimate of integrated variance: (pi/2) times the sum of products of adjacent absolute returns. Where RV includes jumps, BPV excludes them, and the gap between the two is the raw material for jump detection.', anchorSrc: A(dat, 1) },
  { id: 'semivariance', term: 'realized semivariance', def: 'RV split by return sign: RS+ from non-negative returns, RS- from negative ones, with RS+ plus RS- equal to RV exactly. Downside semivariance carries the leverage effect signal.', anchorSrc: A(dat, 2) },
  { id: 'rk', term: 'realized kernel', def: 'A microstructure-noise-robust variance estimator that weights return autocovariances with a flat-top Parzen kernel. On noisy tick data it recovers true variance better than naive tick RV, and the tests prove that property directly.', anchorSrc: A(dat, 5) },
  { id: 'vpin', term: 'VPIN', def: 'Volume-Synchronized Probability of Informed Trading: the mean absolute buy-sell volume imbalance across equal-volume buckets. A daily order-flow toxicity measure from the microstructure layer.', anchorSrc: A(dat, 12) },
  { id: 'tsdb', term: 'TSDB', def: 'The GS internal Time Series Database, queried through gs_quant_internal with eqpad_ prefixed symbols. Source of daily OHLCV, treasury yields, FX, commodities, VIX, and SPX series.', anchorSrc: A(dat, 9) },
  { id: 'chunk-store', term: 'Chunk Store', def: 'The GS internal tick store, accessed via pytickclient. Supplies L1 trades and quotes for the 34 symbol universe plus L2 depth for the E-mini future; raw ticks are the foundation for every realized measure.', anchorSrc: A(dat, 8) },
  { id: 'marquee', term: 'Marquee EDRVOL', def: 'The Marquee dataset carrying the SPX implied volatility surface by tenor and relative strike. Bulk-fetched into a daily panel, it feeds every options-implied feature.', anchorSrc: A(dat, 13) },
  { id: 'vrp', term: 'variance risk premium', def: 'Option-implied variance minus expected realized variance, computed here as (atm_iv/100)^2 - rv*252. Usually positive: investors pay a premium for volatility protection, which is exactly the premium the trading strategies harvest.', anchorSrc: A(fea, 5) },
  { id: 'iv-rv-gap', term: 'IV-RV gap', def: 'The spread between an implied volatility measure and the model\'s RV forecast. Positive gap: options look rich, sell vol. Negative: options look cheap, buy vol. This one number is what the whole pipeline exists to estimate well.', anchorSrc: A(eco, 0) },
  { id: 'kvar', term: 'Kvar', def: 'A variance swap strike. Exec Kvar is the strike actually dealt at GSVIVS execution fills, recovered from option fill prices with the CBOE discrete variance swap formula; it is the production IV input to the signal.', anchorSrc: A(eco, 13) },
  { id: 'gsvivs', term: 'GSVIVS01', def: 'A GS short-volatility variance swap index. The strategy holds it long by default and flips short when the RV forecast exceeds the Kvar; daily P&L is the signal times the next-day index return.', anchorSrc: A(eco, 4) },
  { id: 'straddle', term: 'delta-hedged straddle', def: 'An ATM call plus put with the directional exposure hedged away. What remains is gamma P&L that pays the spread between realized and implied variance, making it the natural instrument for monetizing a vol forecast.', anchorSrc: A(eco, 3) },
  { id: 'dm', term: 'Diebold-Mariano test', def: 'The standard test of equal predictive accuracy between two forecast series, run on their QLIKE loss differential with Newey-West HAC errors. This repo\'s version averages losses per date first so panel lags never cross symbol boundaries.', anchorSrc: A(pev, 15) },
  { id: 'mcs', term: 'Model Confidence Set', def: 'The Hansen et al. 2011 procedure that returns the subset of models statistically indistinguishable from the best, via sequential elimination with a block bootstrap. Membership, not rank, is the honest headline.', anchorSrc: A(pev, 16) },
  { id: 'duan', term: 'Duan correction', def: 'The retransformation applied when log-space forecasts are converted back to variance levels: plain exponentiation is biased low, so predictions are scaled by mean(exp(residuals)). The conditional variant re-estimates it per sample, walk-forward.', anchorSrc: A(pev, 3) },
  { id: 'purge-gap', term: 'purge gap', def: 'A buffer of dates deleted around every CV test block so overlapping RV windows cannot leak across the train/test boundary. Random k-fold is banned outright in this repo for the same reason.', anchorSrc: A(pev, 8) },
  { id: 'walk-forward', term: 'walk-forward CV', def: 'Expanding-window evaluation: the training window grows through time and the test window always sits strictly after it, mimicking live deployment. The panel variant splits on unique dates so all symbols share fold boundaries.', anchorSrc: A(pev, 9) },
  { id: 'tenor-matching', term: 'tenor matching', def: 'Feeding each forecast horizon the implied vol of matching maturity: 0DTE IV for one day ahead, 1 week IV for five days, 1 month IV for twenty two. Trial-032 measured roughly 100 bps of QLIKE from this one idea.', anchorSrc: A(cfg, 8) },
  { id: 'seed-envelope', term: 'seed envelope', def: 'The spread of QLIKE across retrainings that differ only in random seed, measured at 6.6 bps at h=1. Any single-seed improvement smaller than that is noise, which is why one champion was retracted.', anchorSrc: A(mod, 17) },
  { id: 'dsr', term: 'deflated Sharpe ratio', def: 'The Bailey and Lopez de Prado correction for strategy selection luck: the probability that an observed Sharpe beats the maximum expected by chance given how many configurations were tried.', anchorSrc: A(eco, 9) },
  { id: 'gex', term: 'dealer gamma exposure', def: 'The aggregate gamma of SPX option dealers. Its sign determines whether dealer hedging dampens moves (long gamma) or amplifies them (short gamma), so the feature layer encodes sign, regime, and momentum.', anchorSrc: A(fea, 8) },
  { id: 'coala', term: 'CoALA memory', def: 'The cognitive-architecture scheme the agent memory follows: compressed, atomic, linked, actionable files in P0 to P3 priority tiers with hard token budgets that a lint actually enforces.', anchorSrc: A(ops, 4) },
  { id: 'skill', term: 'skill', def: 'A narrow executable capability with declared inputs, outputs, and authority bounds. An agent invokes one by writing a JSON args file, firing a predefined VS Code task, and reading an output file that must end EXIT_CODE=0.', anchorSrc: { file: 'skills/design.md', quote: '3. `SKILL.md` must include a Skill Identity table (Name, Scope, Inputs, Outputs, Authority).', after: 0 } },
  { id: 'qlike-objective', term: 'QLIKE custom objective', def: 'The hand-derived gradient (1 - exp(e)) and hessian (exp(e)) of log-space QLIKE, plugged into LightGBM and XGBoost so the trees split on the exact loss the tournament scores.', anchorSrc: A(mod, 5) },
  { id: 'zero-dte', term: '0DTE IV', def: 'Implied volatility of options expiring the same day: the only implied measure whose window exactly matches a one-day-ahead RV forecast.', anchorSrc: A(fea, 6) },
];

// ---------------------------------------------------------------- map
const map = {
  columnLabels: ['INTERFACE', 'CORE', 'DATA', 'FEATURES', 'MODELS', 'EVALUATION', 'OUTPUT'],
  note: {
    title: 'WHAT IS NOT ON THIS BOARD',
    text: 'Two things are deliberately off the board. src/tests/ (225 files, 55,156 loc) imports every column and drew eleven edges that turned the graph into a hairball; it gets its own stop instead. And 14 modules that the code imports do not exist in this snapshot, including the tournament runner and the HAR model family: see the restore ledger on the setup stop. The survey counts them; the board only draws files that exist.',
  },
  tour: [
    { id: 'n-cli', text: 'Start here. Every interaction is a `vol` subcommand: one primary command, `vol run --config <yaml>`, plus about two dozen utilities for ingestion, auditing, and the live forecast. Each subcommand registers itself, so the surface grows without touching the entry point.' },
    { id: 'n-core', text: 'The hub. registry.py holds three string-to-class maps for models, feature layers, and graph builders. A YAML config names components; the registry turns names into classes. This is why 69 files import it, and why you cannot change it quietly.' },
    { id: 'n-data', text: 'The heaviest lifting. Ticks from [[chunk-store|Chunk Store]], daily series from [[tsdb|TSDB]], the SPX vol surface from [[marquee|Marquee EDRVOL]]. measures.py turns millions of ticks into a handful of daily numbers: [[rv|realized variance]], [[bpv|bipower variation]], jump tests, [[rk|the realized kernel]].' },
    { id: 'n-features', text: 'The design matrix factory: layers 0 to 5, from HAR lags through options-implied, microstructure, cross-asset, and calendar features, each a registered class a config can stack. Suffixes are systematic: _d daily, _w the 5 day mean, _m the 22 day mean.' },
    { id: 'n-models', text: 'The zoo: 24 registered names from nine naive baselines through LightGBM, XGBoost, and seven graph models. One shared contract, and nearly every trainable model optimizes [[qlike|QLIKE]] directly during training. The linear HAR family and the LSTM are imported here but missing from this snapshot.' },
    { id: 'n-pipeline', text: 'The anti-cheating layer: per-symbol normalisers fitted on training rows only, a content-addressed fold cache for expensive sequence models, and the per-sample conditional [[duan|Duan correction]] estimated strictly walk-forward.' },
    { id: 'n-evaluation', text: 'Where claims go to die: [[qlike|QLIKE]] ranking, panel-aware [[dm|Diebold-Mariano]] tests, the [[mcs|Model Confidence Set]], and then the money tests: realistic delta-hedged straddles with a full P&L waterfall, and the [[gsvivs|GSVIVS01]] signal backtest.' },
    { id: 'n-utils', text: 'Last, the quiet dependency: utils/paths.py anchors every cache path to the repo root, and utils/cv.py holds the splitters that make every result walk-forward honest. Everything above imports these; nothing here imports back.' },
  ],
  nodes: [
    { id: 'n-cli', label: 'cli', path: 'src/volforecast/cli/', col: 0, loc: 7342, files: 28,
      role: [
        'One module per subcommand, each exposing a register(subparsers) function that `__main__` calls lazily, so the command surface is owned by the modules that implement it. The primary command is `vol run`, which drives the whole experiment pipeline; around it sit eleven ingest commands, audit and status for data integrity, cache tools, and three experiment-management commands over the trial registry.',
        'Two commands are ends in themselves: `vol forecast` is the live product, an ensemble that predicts next-day RV, compares it to current ATM IV, and prints LONG, SHORT, or FLAT; `vol kvar` prints the GSVIVS signal scoreboard across cached IV sources.',
        'The shell wrappers sit in front: ./vol is hard-guarded to the GS Linux workspace and bootstraps uv, system site-packages, and nix library paths, while vol.cmd on Windows supports only the dev loop.',
      ],
      reads: 'User intent: argv, YAML config paths, and the interactive config picker over `workspace/configs/`.',
      feeds: 'Everything: it triggers ingestion in `data`, experiment runs through `core`, and result browsing in `evaluation`.',
      key_files: [
        { file: 'console.py', purpose: 'shared Rich console singleton and logging setup used by every command' },
        { file: 'config_picker.py', purpose: 'interactive menu over workspace/configs/ YAMLs when vol run gets no --config' },
        { file: 'audit.py', purpose: 'validates every cached parquet against manifest contracts and regenerates data/manifest.json' },
        { file: 'forecast.py', purpose: 'the live signal: multi-model ensemble to LONG / SHORT / FLAT against current ATM IV' },
        { file: 'kvar.py', purpose: 'GSVIVS signal performance tables (Sharpe, drawdown, hit rate) across IV sources' },
      ],
      concepts: ['register() pattern', 'ingest commands', 'live IV-RV signal', 'trial registry'],
      anchorSrc: A(core, 15), anchor_caption: 'The live end product: forecast.py compares the RV forecast to ATM IV and emits a position.' },
    { id: 'n-core', label: 'core + registry', path: 'src/volforecast/', col: 1, loc: 1013, files: 3,
      role: [
        'The package root holds three files that everything else orbits. The `__init__` docstring states the thesis: enrich HAR baselines with microstructure, options, and cross-asset features via gradient boosting until the QLIKE gain is statistically significant and tradeable.',
        '`__main__.py` is the single entry point: it assembles the parser, applies the ingest gate, then routes every run mode through the tournament, wiring progress callbacks for folds, Optuna trials, MCS statistics, straddle P&L, and SHAP into the terminal display, and finally updates the trial registry from metrics.json.',
        'registry.py is why this tiny package is imported by 69 files: three dicts map string names to model, feature-layer, and graph-builder classes, so YAML configs can name components without importing them.',
      ],
      reads: 'A YAML experiment file, resolved into an ExperimentConfig (whose source module is missing from this snapshot).',
      feeds: 'Dispatch: every other package is reached from here by name lookup.',
      key_files: [
        { file: '__init__.py', purpose: 'the thesis docstring and package version' },
        { file: '__main__.py', purpose: 'CLI entry: parser assembly, ingest gate, tournament routing, trial registry update' },
        { file: 'registry.py', purpose: 'MODEL_REGISTRY, FEATURE_REGISTRY, GRAPH_REGISTRY and their decorators' },
      ],
      concepts: ['registry pattern', 'ingest gate', 'tournament routing', 'trial registry'],
      anchorSrc: A(core, 12), anchor_caption: 'Three registries, one hub: the reason 69 files import this module.' },
    { id: 'n-data', label: 'data', path: 'src/volforecast/data/', col: 2, loc: 9195, files: 21,
      role: [
        'The ingestion and caching tier: it turns three GS market data services into per-symbol parquet caches and model-ready tensors. Chunk Store supplies raw L1 ticks for the 34 symbol universe, TSDB supplies daily OHLCV and cross-asset series, and Marquee EDRVOL_PERCENT supplies the SPX implied vol surface.',
        'measures.py is the scientific heart: realized variance from squared 5 minute returns, jump-robust bipower variation, the BNS z-test splitting RV into continuous and jump parts, Patton-Sheppard semivariances, realized quarticity, and a Parzen realized kernel for noise robustness. Every formula is paper-anchored and gold-value tested.',
        'Beyond daily scalars it builds sequences: micro.py aggregates ticks into 10 second signed-volume bars with VPIN and order-flow aggregates, and sequence_cache.py pre-stacks them into padded float32 tensors so deep models train as pure GPU ops. Cache writes are atomic (temp file then rename) and merging, never destructive.',
      ],
      reads: 'Chunk Store ticks, TSDB daily series, and the Marquee vol surface, via GS-network-only client libraries.',
      feeds: 'Daily panels to `features`, sequence tensors to the deep models, and IV panels to the signal stack.',
      key_files: [
        { file: 'measures.py', purpose: 'the canonical estimators: RV, BPV, semivariances, jump tests, realized kernel' },
        { file: 'rv_panel.py', purpose: 'streaming, checkpointed builder of the per-symbol daily RV panel' },
        { file: 'micro.py', purpose: '10 second signed-volume bars, VPIN, order flow; sequences for LSTM / TCN' },
        { file: 'sequence_cache.py', purpose: 'padded (dates, bars, features) tensors cached as .pt, leakage-free normalisation' },
        { file: 'iv_features.py', purpose: 'causal shift(1) IV features: VRP, term slope, butterfly, vol of VIX' },
        { file: 'gsvivs_kvar.py', purpose: 'recovers the exact execution Kvar from GSVIVS01 option fills via the CBOE formula' },
      ],
      concepts: ['realized variance', 'bipower variation', 'jump detection', 'VPIN', 'atomic parquet caches', 'IV surface'],
      anchorSrc: A(dat, 1), anchor_caption: 'Jump-robust bipower variation, one of the estimators computed for every symbol-day.' },
    { id: 'n-features', label: 'features', path: 'src/volforecast/features/', col: 3, loc: 3110, files: 18,
      role: [
        'Eighteen registered feature layers turn daily measures and enriched market columns into the design matrix. The numbered spine is layers 0 to 5: HAR core (log RV at d/w/m horizons plus HARQ quarticity terms), asymmetry (semivariances, jumps), options (VRP, skew, term slope, 0DTE tenors, IV x RV interactions), microstructure (VPIN, Kyle lambda, Amihud), cross-asset (rates, FX, commodities, spillover), and calendar (FOMC, NFP, OpEx proximity).',
        'Registered extensions go further: dealer gamma exposure, implied and realized correlation, the 73 feature GSVIVS01 signal set, long-memory lags for h=22, Markov regime probabilities, and noise-robust estimators. Each layer is a class with a uniform compute(daily_data, context) contract, so a config stacks them declaratively and order matters only where documented.',
        'Naming is systematic and worth memorising: _d is the daily value, _w the 5 day rolling mean, _m the 22 day mean; momentum features use d_*_1d, d_*_5d and z_* rolling z-scores.',
      ],
      reads: 'Daily RV panels and enriched market columns from `data`; caches under data/raw/ for GEX, correlation, and options data.',
      feeds: 'The design matrix consumed by every tabular model in `models`.',
      key_files: [
        { file: 'har.py', purpose: 'Layer 0: the HAR backbone plus HARQ measurement-quality terms' },
        { file: 'options.py', purpose: 'Layer 2: VRP, skew, term slope, 0DTE / 1W tenors, IV x log RV interactions' },
        { file: 'gsvivs_signals.py', purpose: 'the exact 73 feature input set of the GSVIVS01 short-variance strategy' },
        { file: 'transforms.py', purpose: 'safe_log and the lagged _d / _w / _m column factory' },
        { file: 'calendar.py', purpose: 'Layer 5: FOMC (hardcoded 2015 to 2026), NFP, OpEx proximity' },
      ],
      concepts: ['feature layers 0-5', 'HARQ', '0DTE IV', 'dealer gamma', 'suffix naming'],
      anchorSrc: A(fea, 0), anchor_caption: 'The package docstring declaring the layer architecture.' },
    { id: 'n-graphs', label: 'graphs', path: 'src/volforecast/graphs/', col: 3, loc: 826, files: 9,
      role: [
        'Point-in-time graph construction for the graph models: a graph used to forecast date t is estimated only on data up to t, re-estimated every refit_every trading days, and frozen between refits, so the network structure itself cannot leak the future.',
        'Registered builders cover correlation threshold and kNN graphs, GLASSO conditional-independence graphs, the directed Diebold-Yilmaz spillover graph from a VAR variance decomposition, structural sector and identity graphs, a factor-residual wrapper, and a calm/stress regime blend. Diagnostics watch density explosions and refit-to-refit edge stability.',
      ],
      reads: 'Rolling windows of the log RV panel and returns from `data`.',
      feeds: 'GraphSnapshot objects (COO edges plus weights) to the GNN and GHAR models in `models`.',
      key_files: [
        { file: 'base.py', purpose: 'GraphSnapshot, the GraphBuilder protocol, and the point-in-time schedule' },
        { file: 'spillover.py', purpose: 'directed Diebold-Yilmaz graph from a generalized FEVD' },
        { file: 'glasso.py', purpose: 'sparse precision-support graph: edges are conditional dependence' },
      ],
      concepts: ['point-in-time protocol', 'GraphSnapshot', 'spillover graph', 'edge stability'],
      anchorSrc: A(eco, 14), anchor_caption: 'The point-in-time protocol that keeps look-ahead out of the graph structure.' },
    { id: 'n-models', label: 'models', path: 'src/volforecast/models/', col: 4, loc: 9802, files: 22,
      role: [
        'The model zoo: 24 registered names, all speaking the _BaseModel contract, so the harness treats a random walk and a graph attention network identically. Families: nine naive baselines that set the QLIKE floor; the linear HAR family (missing from this snapshot, its base class and tuning grid remain); gradient boosting via LightGBM, its DART variant, and XGBoost; a seven-model graph suite; and five ensembles including bagging, calibration, stacking, and a regime-dependent blend.',
        'The signature move is that training loss equals evaluation loss: LightGBM and XGBoost run a hand-derived QLIKE gradient and hessian as a custom objective, and the torch graph models share a QLIKE loss, all in log RV space.',
        'The graph suite is built for honest attribution: ghar with zero adjacency recovers pooled HAR exactly, gsp_har nests QLIKE-HAR at initialization, and stid deliberately ignores edges so that any "graph" gain must beat pooling plus asset identity first. The research journal records the outcome: all five graph trials landed within 1 bp of the linear baseline.',
      ],
      reads: 'Feature matrices from `features`, graph snapshots from `graphs`, sequence tensors from `data`.',
      feeds: 'Out-of-sample log RV predictions per fold into `evaluation`.',
      key_files: [
        { file: '_base.py', purpose: 'the shared contract: REQUIRED_LAYERS, capability flags, save / load' },
        { file: 'lightgbm.py', purpose: 'the workhorse: QLIKE custom objective, Optuna tuning, TreeSHAP selection' },
        { file: 'xgboost.py', purpose: 'independent cross-check of LightGBM with the same objective; current h=1 champion' },
        { file: 'naive.py', purpose: 'nine baselines from random walk to VIX-implied that set the QLIKE floor' },
        { file: 'gnn.py', purpose: 'GATv2 attention over per-date correlation graphs, shared QLIKE loss for torch models' },
        { file: 'stid.py', purpose: 'the deflation control: same harness, edges ignored on purpose' },
      ],
      concepts: ['model registry', 'QLIKE objective', 'naive floor', 'deflation control', 'ensembles'],
      anchorSrc: A(mod, 5), anchor_caption: 'The QLIKE gradient and hessian LightGBM trains on: loss equals metric.' },
    { id: 'n-pipeline', label: 'pipeline', path: 'src/volforecast/pipeline/', col: 4, loc: 1307, files: 6,
      role: [
        'Fold-level orchestration between the CV splitters and the models, built to make cheating structurally difficult. norm.py fits per-symbol z-score normalisers from training rows only; feature_selection.py runs Boruta-style TreeSHAP shadow selection inside each outer fold; graph_data.py bridges the pooled panel into per-date graph dicts.',
        'fold_cache.py content-addresses expensive sequence-model training: a fingerprint over config, horizon, fold, split dates, and base-model predictions decides whether a fold can be skipped, so nothing retrains by accident and nothing is reused wrongly. conditional_duan.py upgrades the global log-to-level bias correction to a per-sample one, trained walk-forward on prior folds\' residuals or a VVIX proxy.',
      ],
      reads: 'Fold definitions from utils/cv.py, features and sequences from upstream.',
      feeds: 'Clean, leakage-controlled inputs to `models`; corrected predictions to `evaluation`.',
      key_files: [
        { file: 'fold_cache.py', purpose: 'fingerprint-keyed skip of already-trained sequence folds' },
        { file: 'norm.py', purpose: 'per-symbol z-scoring fitted on training data only' },
        { file: 'conditional_duan.py', purpose: 'per-sample walk-forward Duan correction, optional VVIX proxy' },
      ],
      concepts: ['fold fingerprint', 'shadow features', 'conditional Duan', 'per-symbol normalisation'],
      anchorSrc: A(pev, 10), anchor_caption: 'The fold cache fingerprint: every input that affects the trained model.' },
    { id: 'n-evaluation', label: 'evaluation', path: 'src/volforecast/evaluation/', col: 5, loc: 7031, files: 14,
      role: [
        'The tournament and the money. statistical_tests.py builds one ranked table per horizon: QLIKE, panel-aware Diebold-Mariano against the baseline, Mincer-Zarnowitz efficiency, Model Confidence Set membership via block bootstrap, plus a calm/turbulent split so you can see where a model earns its keep.',
        'Then forecasts are traded on paper, three ways: delta-hedged straddles, from an analytic engine with the full P&L waterfall (tenor-decayed gamma, vanna, volga, maturity-widening spreads, Boyle-Emanuel hedge-error variance) to a bar-by-bar simulator on 15 minute bars; the GSVIVS01 index signal across six registered IV sources with four sizing modes; and vol-targeting portfolios. Sharpe ratios get deflated for selection luck and bracketed with bootstrap confidence intervals and cost bands.',
        'checkpoint.py makes tournaments resumable at model granularity with atomic writes, and explainability.py adds TreeSHAP and a from-scratch ALE implementation so the tree models can be interrogated.',
      ],
      reads: 'Per-fold predictions from the models, IV caches and index levels from `data`.',
      feeds: 'metrics.json, the tournament dashboard, and the trial registry.',
      key_files: [
        { file: 'metrics.py', purpose: 'QLIKE and friends, plus the Duan retransformation' },
        { file: 'statistical_tests.py', purpose: 'DM, MCS, Mincer-Zarnowitz, the ranked tournament table' },
        { file: 'realistic_straddle.py', purpose: 'the honest straddle engine: full P&L waterfall and deflated Sharpe' },
        { file: 'gsvivs.py', purpose: 'GSVIVS01 backtest orchestration across six IV sources' },
        { file: 'checkpoint.py', purpose: 'crash-safe per-model resume for tournaments' },
      ],
      concepts: ['tournament table', 'turbulence split', 'P&L waterfall', 'deflated Sharpe', 'cost bands'],
      anchorSrc: A(pev, 17), anchor_caption: 'One ranked table: every statistical test in a single tournament view.' },
    { id: 'n-reporting', label: 'reporting', path: 'src/volforecast/reporting/', col: 6, loc: 461, files: 9,
      role: [
        'The HTML experiment report, honestly unfinished: the orchestrator and five of six section renderers are documented stubs that raise NotImplementedError, pointing at the plan file that specifies them. The one real section is economic value: it aligns predictions with market data, lags IV by one day to avoid look-ahead, runs the realistic straddle engine, and renders Sharpe, DSR, and cost-band tables.',
      ],
      reads: 'A finished experiment directory: metrics, predictions, config snapshot.',
      feeds: 'A single-file HTML report (when finished).',
      key_files: [
        { file: 'html_report.py', purpose: 'orchestrator stub documenting the seven-step assembly plan' },
        { file: 'sections/economic_value.py', purpose: 'the implemented section: realistic straddle metrics as HTML' },
      ],
      concepts: ['report sections', 'look-ahead avoidance'],
      anchorSrc: A(eco, 19), anchor_caption: 'The implemented section lags IV by one day before backtesting.' },
    { id: 'n-visualization', label: 'visualization', path: 'src/volforecast/visualization/', col: 6, loc: 102, files: 2,
      role: [
        'Two files survive here: the package docstring and lineage.py, which renders a model lineage spec (base model init score, LSTM feature stack, daily features) as a Mermaid flowchart for dashboards. The dashboard builder itself, visualization/dashboard.py, is one of the modules this snapshot lost.',
      ],
      reads: 'Model lineage specs from tournament code.',
      feeds: 'Mermaid flowchart strings to the dashboard.',
      key_files: [
        { file: 'lineage.py', purpose: 'model lineage to Mermaid flowchart' },
      ],
      concepts: ['model lineage'] },
    { id: 'n-utils', label: 'utils', path: 'src/volforecast/utils/', col: 1, loc: 1552, files: 7,
      role: [
        'The quiet foundation, imported by eight of the ten groups on this board and importing none of them back. paths.py anchors every cache directory to the repo root by marker-file search, defining the whole data/raw and data/processed layout, so caches resolve identically from any working directory.',
        'cv.py is the leakage firewall: purged k-fold, blocked k-fold, expanding and rolling windows, and the panel-aware expanding window that splits on unique dates. Its docstring bans random k-fold outright as catastrophic look-ahead bias, and policy repeats the ban at the API level.',
      ],
      reads: 'Nothing from this board.',
      feeds: 'Path resolution and CV splits to everything above.',
      key_files: [
        { file: 'paths.py', purpose: 'repo-root-anchored resolvers for every cache directory' },
        { file: 'cv.py', purpose: 'the CV splitters: purged, blocked, expanding, rolling, panel-aware' },
        { file: 'manifest.py', purpose: 'the ingestion manifest read by vol status and vol audit' },
      ],
      concepts: ['cache layout', 'purged CV', 'walk-forward'],
      anchorSrc: A(pev, 7), anchor_caption: 'The house rule, stated where the splitters live.' },
  ],
  edges: [
    { a: 'n-core', b: 'n-graphs', n: 6 }, { a: 'n-core', b: 'n-utils', n: 2 },
    { a: 'n-cli', b: 'n-core', n: 6 }, { a: 'n-cli', b: 'n-data', n: 48 },
    { a: 'n-cli', b: 'n-evaluation', n: 1 }, { a: 'n-cli', b: 'n-pipeline', n: 4 },
    { a: 'n-cli', b: 'n-utils', n: 33 }, { a: 'n-data', b: 'n-core', n: 2 },
    { a: 'n-data', b: 'n-utils', n: 22 }, { a: 'n-evaluation', b: 'n-utils', n: 3 },
    { a: 'n-features', b: 'n-core', n: 17 }, { a: 'n-features', b: 'n-data', n: 17 },
    { a: 'n-features', b: 'n-utils', n: 3 }, { a: 'n-models', b: 'n-core', n: 37 },
    { a: 'n-models', b: 'n-data', n: 3 }, { a: 'n-models', b: 'n-evaluation', n: 6 },
    { a: 'n-models', b: 'n-graphs', n: 1 }, { a: 'n-models', b: 'n-pipeline', n: 2 },
    { a: 'n-models', b: 'n-utils', n: 5 }, { a: 'n-pipeline', b: 'n-evaluation', n: 2 },
    { a: 'n-pipeline', b: 'n-graphs', n: 1 }, { a: 'n-pipeline', b: 'n-utils', n: 4 },
    { a: 'n-reporting', b: 'n-evaluation', n: 1 },
  ],
};

// ---------------------------------------------------------------- missing-module ledger
const MISSING = [
  ['<code>volforecast/config.py</code>', 'ExperimentConfig, the YAML schema every stage parses', '257'],
  ['<code>volforecast/data/edrvol.py</code>', 'loader for all IV, EDRVS and exec-Kvar caches', '106'],
  ['<code>volforecast/pipeline/runner.py</code>', 'the Pipeline class the integration tests drive', '70'],
  ['<code>volforecast/models/har_family.py</code>', 'the linear HAR / ridge / lasso model family', '66'],
  ['<code>volforecast/constants.py</code>', 'SYMBOL_UNIVERSE, field lists, timezone constants', '60'],
  ['<code>volforecast/models/lstm.py</code>', 'the LSTM sequence model (its tuning harness survives)', '42'],
  ['<code>volforecast/evaluation/tournament.py</code>', 'run_har_tournament, the tournament runner itself', '31'],
  ['<code>volforecast/visualization/dashboard.py</code>', 'the Plotly dashboard builder', '25'],
  ['<code>volforecast/cli/ingest_iv.py</code>', 'the IV ingestion subcommand (breaks vol --help)', '22'],
  ['<code>volforecast/evaluation/_parallel.py</code>', 'pooled parallel model execution', '12'],
  ['<code>volforecast/evaluation/_model_utils.py</code>', 'shared model helpers', '7'],
  ['<code>volforecast/data/vix_futures.py</code>', 'VIX futures loader', '3'],
  ['<code>volforecast/features/tree_expansion.py</code>', 'the tree_expansion feature layer (expansion.py survives)', '3'],
  ['<code>volforecast/features/iv_surface.py</code>', 'the iv_surface feature layer', '2'],
];

// ---------------------------------------------------------------- tracks
export const payload = {
  contract: 'trailhead/verified@3-template',
  repo: { name: 'ml-vol-estimator', commit: 'nogit-1c4f5dc3', generated_at: '2026-07-30T23:59:00Z' },
  report: { tool_version: 'template 1.0 (hand-built target)', duration_s: 0,
    regen: 'Hand-built target artifact. Rebuild: node hackathon/template/build.mjs; re-check: node hackathon/template/verify.mjs. Every anchor re-resolved from a verbatim quote and sha256-hashed against the snapshot; dash characters in captured output are transliterated to hyphens.' },
  map,
  glossary,
  files: {},
  dropped: [],
  tracks: [
    // ================================================== ORIENT
    { title: 'ORIENT', minutes: 18, stops: [
      { id: 'cover', title: 'What you are looking at', kind: 'stop', minutes: 3,
        lede: 'A verified walkthrough of ml-vol-estimator, the ML realized volatility forecasting platform, generated from snapshot nogit-1c4f5dc3. Every underlined sentence is anchored to a line range in this repo and re-checked after it was written; click one and the evidence opens under it. Dotted terms open the glossary. Claims whose anchors failed were deleted, and the count is in the top bar.',
        blocks: [
          { type: 'stats', items: [
            { v: '96,897', l: 'lines of code', s: '455 Python files of 1,063 total' },
            { v: '24', l: 'registered models', s: 'naive floor to graph attention' },
            { v: '18', l: 'feature layers', s: 'HAR core to dealer gamma' },
            { v: '209', l: 'test files', s: 'roughly 2,700 test functions' },
            { v: '48', l: 'agent skills', s: 'plus 5 personas, 15 workflows' },
            { v: '14', l: 'modules lost in restore', s: 'counted, not hidden', color: 'inf' },
          ] },
          { type: 'callout', level: 'info', title: 'BEFORE YOU START',
            text: 'The repo is two things at once: a Python package (`volforecast`) that forecasts next-day stock volatility and trades the forecast, and an operating system for GitHub Copilot agents that do the day-to-day research. This walkthrough covers both. It was built from a QR-video restore of the GS repo, so a known list of 14 modules is missing; where that bites, this page says so instead of writing around it.' },
          { type: 'table', caption: 'Generation record', sortable: false,
            columns: ['FIELD', 'VALUE'],
            rows: [
              ['repository', '<code>ml-vol-estimator</code> (package <code>volforecast</code> 0.2.0)'],
              ['snapshot', '<code>nogit-1c4f5dc3</code> · QR restore of 2026-07-06, no git history'],
              ['surveyed', '2026-07-30 · 364 modules in 11 groups on the board'],
              ['entry point', '<code>volforecast.__main__:main</code> via the <code>vol</code> wrapper'],
              ['commands executed', '5 (4 failing, all real output)'],
              ['est. time', 'about 95 minutes, checkpoints included'],
            ] },
        ] },
      { id: 'five', title: 'Five sentences', kind: 'stop', minutes: 4,
        lede: 'If you read nothing else, read these. Every one is anchored; the last is marked inferred because an absence cannot be anchored to a line.',
        blocks: [
          { type: 'prose', claims: [
            C(core, 0, 'This repo forecasts next-day stock market volatility with machine learning: its stated thesis is to progressively enrich [[har|HAR]] baselines with microstructure, options-implied, and cross-asset features via gradient boosting, until the [[qlike|QLIKE]] improvement is statistically significant and the [[iv-rv-gap|IV-RV gap]] it implies is tradeable.'),
            { text: 'Its raw material is GS market data: tick-level trades from [[chunk-store|Chunk Store]], daily OHLCV and cross-asset series from [[tsdb|TSDB]], and the SPX implied volatility surface from [[marquee|Marquee]], all cached locally as parquet.',
              anchor: { file: 'skills/DATA_INGEST/SKILL.md', quote: '- **Source:** Chunk Store via `pytickclient`\n- **Fields:** Trade price, size, BBO, timestamps', before: 3, after: 6 } },
            C(pev, 17, 'Models do not just report a score, they compete: every run is a tournament that ranks the field by [[qlike|QLIKE]] and backs the ranking with [[dm|Diebold-Mariano]] tests, Mincer-Zarnowitz efficiency regressions, and [[mcs|Model Confidence Set]] membership.'),
            C(eco, 0, 'Winning forecasts are then traded on paper: when implied volatility is rich against the forecast the [[straddle|delta-hedged straddle]] engine sells vol, when cheap it buys, and the same gap drives the [[gsvivs|GSVIVS01]] index signal.'),
            C(aos, 0, 'The other half of the repo is not Python: it is an operating system for GitHub Copilot agents, five primitives (Persona, Skill, Memory, Workflow, Policy) that let an agent run this pipeline without breaking its rules.'),
            INF('What it is not: a live trading system. Nothing listens on a socket, every entry point is a batch command that runs to completion, and the only thing resembling an order is a printed LONG, SHORT, or FLAT.'),
          ] },
          { type: 'callout', level: 'inferred', title: 'WHY THE LAST SENTENCE IS AMBER',
            text: 'An absence cannot be anchored to a line of code. Where this page searched and found nothing, it says inferred rather than dressing the sentence up as verified. Every amber mark in this document means the same thing: plausible, unproven.' },
        ] },
      { id: 'map', title: 'The map', kind: 'stop', minutes: 6,
        lede: 'The real import graph, laid out as the pipeline flows: interface to core to data to features to models to evaluation to output. Edges stay faint until you hover a module; click any module for the full story, or take the guided tour.',
        blocks: [
          { type: 'graph' },
          { type: 'prose', claims: [
            C(core, 12, 'The most-imported module on the board is the registry: three string-to-class dicts (models, feature layers, graph builders) that let a YAML config name components without importing them, which is why 69 files point at it.'),
            INF('The columns are ordered so that value flows left to right: commands trigger ingestion, data becomes features, features feed models, models are judged, judgments become reports. Edges pointing right-to-left are almost all imports of the registry and utils, the two shared hubs.'),
          ] },
        ] },
      { id: 'where', title: 'Where the code lives', kind: 'stop', minutes: 4,
        lede: 'The same information as the map, as a sortable list, plus the half of the repo that is not a Python package at all.',
        blocks: [
          { type: 'table', caption: 'src/ packages. Purpose summarised from each package docstring; LOC and file counts from the survey.', sortable: true,
            columns: ['PATH', 'PURPOSE', 'FILES', 'LOC'],
            rows: [
              ['<code>src/volforecast/</code>', 'package root: thesis, entry point, registry', '3', '1,013'],
              ['<code>src/volforecast/data/</code>', 'ticks, OHLCV and IV surfaces to parquet caches and tensors', '21', '9,195'],
              ['<code>src/volforecast/cli/</code>', 'one module per vol subcommand', '28', '7,342'],
              ['<code>src/volforecast/features/</code>', 'feature layers 0-5 plus registered extensions', '18', '3,110'],
              ['<code>src/volforecast/models/</code>', 'the 24-model zoo behind one contract', '22', '9,802'],
              ['<code>src/volforecast/pipeline/</code>', 'fold orchestration: normalisers, caches, Duan correction', '6', '1,307'],
              ['<code>src/volforecast/evaluation/</code>', 'tournament statistics and economic backtests', '14', '7,031'],
              ['<code>src/volforecast/graphs/</code>', 'point-in-time graph construction for GNN models', '9', '826'],
              ['<code>src/volforecast/utils/</code>', 'paths and the CV splitters everything trusts', '7', '1,552'],
              ['<code>src/tests/</code>', 'the largest subsystem: unit, integration, formula registry', '225', '55,156'],
            ] },
          { type: 'table', caption: 'The agent operating layer, outside src/. Counts verified on disk; the README advertises stale higher numbers.', sortable: false,
            columns: ['PATH', 'WHAT IT IS', 'COUNT'],
            rows: [
              ['<code>skills/</code>', 'executable agent capabilities: 8 ML vol skills, 40 GS infrastructure', '48 skills'],
              ['<code>personas/</code>', 'reasoning styles with hard cannot-do bounds', '5 active'],
              ['<code>workflows/</code>', 'keyword-dispatched state machines', '15'],
              ['<code>policy/</code>', 'non-negotiable rules: ML constraints, subagent protocol', '12 documents'],
              ['<code>memory/</code>', 'CoALA knowledge base with P0-P3 tiers and token budgets', '43 validated files'],
              ['<code>workspace/</code>', 'configs, research journal, 21-check governance lint', '100+ trial configs'],
            ] },
        ] },
      { id: 'cp-a', title: 'Checkpoint A', kind: 'cp', minutes: 3, blocks: [
        { type: 'checkpoint', id: 'cp-a1', kind: 'single',
          prompt: 'Which module does the rest of this repo import the most?',
          options: ['<code>volforecast.utils.paths</code>', '<code>volforecast.data.sequence_cache</code>', '<code>volforecast.registry</code>', '<code>volforecast.models._base</code>'],
          answer: 2,
          provenance: 'survey.json per-file fan-in over the import graph: registry is imported by 69 modules, the most in the repo; utils.paths is next at 36.',
          explanation: 'The registry maps names to classes for models, feature layers, and graph builders, so nearly everything touches it. Whatever the rest of a repo points at is where its assumptions live; it is the thing you cannot change quietly.' },
        { type: 'checkpoint', id: 'cp-a2', kind: 'single',
          prompt: 'You type vol run with no --config argument. What happens?',
          options: ['An interactive picker lists YAML configs from workspace/configs/, newest first, completed trials ticked', 'It errors out because --config is required', 'It runs a built-in default tournament', 'It prompts for a symbol list'],
          answer: 0,
          provenance: 'src/volforecast/__main__.py falls back to pick_config() when args.config is None; cli/config_picker.py builds the mtime-sorted menu.',
          explanation: 'The run handler calls the config picker, which scans workspace/configs/ sorted by modification time and marks configs whose trial registry status is completed.' },
        { type: 'checkpoint', id: 'cp-a3', kind: 'single',
          prompt: 'This repo is registered to one console script. Which file does execution start in?',
          options: ['<code>src/volforecast/cli/audit.py</code>', '<code>src/volforecast/__main__.py</code>', '<code>src/volforecast/registry.py</code>', '<code>workspace/lint/lint_all.py</code>'],
          answer: 1,
          provenance: 'src/pyproject.toml [project.scripts] declares volforecast = volforecast.__main__:main; the survey lists it as the high-confidence entry point.',
          explanation: 'Both the console script and python -m volforecast land in __main__.py, which assembles the parser and routes every run through the tournament.' },
      ] },
    ] },
    // ================================================== GET IT RUNNING
    { title: 'GET IT RUNNING', minutes: 15, stops: [
      { id: 'setup', title: 'Setup, honestly', kind: 'stop', minutes: 6,
        lede: 'Every command here was executed on this machine during generation. The output is real, the timings are real, and so are the failures, which on this snapshot are the interesting part.',
        blocks: [
          { type: 'command', cmd: 'python -c "import volforecast"', cwd: 'src', exit: 0, dur: '44 ms',
            capture: 'import.txt', env: ENV,
            predict: 'This snapshot is known to be missing 14 modules. Does a bare import of the package still pass?' },
          { type: 'prose', claims: [
            C(core, 10, 'The import passes because the package defers heavy work: but the moment you ask for more, the missing modules bite, starting with volforecast.config, the ExperimentConfig module that the run command imports and this snapshot does not contain.'),
          ] },
          { type: 'command', cmd: 'python -m volforecast --help', cwd: 'src', exit: 1, dur: '118 ms',
            capture: 'volhelp.txt', env: ENV,
            broken: 'ModuleNotFoundError: No module named volforecast.cli.ingest_iv',
            hypothesis: 'The parser imports every subcommand module while assembling help text, so the first missing CLI module kills even --help. On the GS original this passes; the loss is a restore artifact.',
            predict: 'Even printing the help text requires importing every subcommand module. Does --help survive?' },
          { type: 'table', caption: 'The restore ledger: modules the code imports that do not exist in this snapshot. Import-site counts from the survey; the walkthrough is honest about the holes rather than writing around them.', sortable: true,
            columns: ['MISSING MODULE', 'WHAT IT WAS', 'IMPORT SITES'],
            rows: MISSING },
          { type: 'callout', level: 'broken', title: 'WHAT THIS MEANS FOR YOU',
            text: 'On this snapshot, `vol run` cannot execute: config, tournament runner, and the linear model family are gone. Everything else in this walkthrough still holds: the estimators, features, models, evaluation machinery, tests, and the agent layer are intact and readable. If you are on the GS original, none of this applies.' },
        ] },
      { id: 'green', title: 'Your first signal', kind: 'stop', minutes: 4,
        lede: 'On a healthy checkout the first green signal is the test suite. Here is exactly how far this snapshot gets, with real output.',
        blocks: [
          { type: 'command', cmd: 'python -m pytest --collect-only -q tests', cwd: 'src', exit: 2, dur: '12.1 s',
            capture: 'collect.txt', elide: { head: 26, tail: 10 }, env: ENV },
          { type: 'prose', claims: [
            C(tst, 2, 'The suite itself is built to run anywhere: the integration conftest states that tests exercise multi-component workflows with synthetic data and need neither network access nor real data files.'),
            INF('1,603 tests collect cleanly; the 61 collection errors all trace to the missing modules, most through one chain: conftest.py imports data.chunk_store, which imports the lost constants module. One missing file poisons collection for every test behind it.'),
          ] },
          { type: 'command', cmd: 'python -m pytest tests/unit/graphs -q', cwd: 'src', exit: 1, dur: '2.7 s',
            capture: 'graphs.txt', elide: { head: 24, tail: 3 }, env: ENV,
            broken: 'ModuleNotFoundError: No module named volforecast.constants (via tests/conftest.py importing data.chunk_store)' },
          { type: 'callout', level: 'info', title: 'THE SMOKE CHECK THAT DOES PASS',
            text: 'python -c "import volforecast" (previous stop, exit 0 in 44 ms) proves the package resolves from the source root. On the GS original, the dev loop is ./vol test, which runs the non-slow suite; the wrapper is OS-guarded, so on Windows use vol.cmd or the VS Code tasks.' },
        ] },
      { id: 'devloop', title: 'The dev loop', kind: 'stop', minutes: 5,
        lede: 'How work actually happens here: one wrapper, one governance gate, and a rule that agents and humans share the same rails.',
        blocks: [
          { type: 'command', cmd: 'python workspace/lint/lint_all.py', cwd: '.', exit: 1, dur: '3.5 s',
            capture: 'lintall.txt', elide: { head: 58, tail: 10 }, env: ENV,
            broken: 'FAILED (2/21): broken refs, canonical schema (both are restore artifacts: they chase references into the missing files)' },
          { type: 'prose', claims: [
            C(ops, 0, 'The quality gate is workspace/lint/lint_all.py: a stdlib-only runner that registers 21 governance checks in a typed registry and runs them in parallel, exiting zero only when all pass.'),
            C(ops, 1, 'These checks go far beyond style: they audit the pinned subagent model, keep the vol CLI and its documentation in three-way parity, scan for secrets, enforce memory token budgets, and verify that every VS Code task honours the args-file contract.'),
            C(ops, 14, 'The gate cannot rot: a repo-local pre-commit hook runs the same 21 checks with always_run true at every commit, a lesson learned after an earlier CI trigger silently watched the wrong branches.', { after: 1 }),
            C(ops, 11, 'GitHub Actions CI is explicitly a mirror-only safety net: the real remote is GS GitLab where Actions never fire, so ci.yml runs ruff, mypy, and pytest with the project\'s only coverage gate (30 percent) on the personal mirror alone.'),
            C(ops, 15, 'On the GS Windows surface, compute goes through 45 predefined VS Code tasks that pass parameters as JSON args files under workspace/tmp/, so no agent ever composes free-form shell.'),
          ] },
        ] },
      { id: 'cp-b', title: 'Checkpoint B', kind: 'cp', minutes: 3, blocks: [
        { type: 'checkpoint', id: 'cp-b1', kind: 'single',
          prompt: 'pytest collection explodes with 61 errors on this snapshot. The chain starts in tests/conftest.py. Which missing module is at the end of it?',
          options: ['<code>volforecast.constants</code>', '<code>volforecast.config</code>', '<code>volforecast.pipeline.runner</code>', '<code>volforecast.evaluation.tournament</code>'],
          answer: 0,
          provenance: 'tests/conftest.py imports volforecast.data.chunk_store; chunk_store.py line 35 imports volforecast.constants, which is absent. Captured in the pytest run above.',
          explanation: 'The conftest mocks the tick processor by importing chunk_store, and chunk_store needs CHUNKDB and SYMBOL_UNIVERSE from constants. The other three are also missing, but they break different doors.' },
        { type: 'checkpoint', id: 'cp-b2', kind: 'single',
          prompt: 'How many governance checks does workspace/lint/lint_all.py run, and how many failed on this snapshot?',
          options: ['21 checks, 2 failing', '45 checks, 2 failing', '21 checks, 0 failing', '9 checks, 5 failing'],
          answer: 0,
          provenance: 'The LINTS registry in workspace/lint/lint_all.py holds 21 entries; the captured run above ends FAILED (2/21): broken refs, canonical schema.',
          explanation: 'Both failures chase references into the restore gaps. 45 is the number of VS Code tasks, a different surface.' },
      ] },
    ] },
    // ================================================== THE FORECASTING MACHINE
    { title: 'THE FORECASTING MACHINE', minutes: 32, stops: [
      { id: 'config', title: 'An experiment is a YAML file', kind: 'stop', minutes: 5,
        lede: 'Everything the pipeline does is driven by one config file per experiment. Learn this shape and you can read every one of the 100+ trials in workspace/configs/.',
        blocks: [
          { type: 'prose', claims: [
            C(cfg, 0, 'Every experiment is one YAML file parsed by ExperimentConfig.from_yaml; the canonical example in workspace/configs/ documents every accepted field, and names the missing config.py as its source of truth.'),
            C(cfg, 1, 'A config picks a symbol universe of up to 34 tickers and forecasts at three horizons: 1, 5, and 22 trading days, that is daily, weekly, and monthly.'),
            C(cfg, 2, 'Feature layers are order-sensitive, and the config file itself documents the two hard rules: iv_surface must precede options because it supplies the data options consumes, and tree_expansion must come last because it expands everything before it.'),
            { text: 'Model choice is a one-line registry name: the same YAML slot accepts lightgbm, xgboost, seven graph models, ensembles, deep sequence models, or a naive baseline, with no code changes.',
              anchor: { file: 'workspace/configs/_CANONICAL_EXAMPLE.yaml', quote: '  #   ML:          lightgbm, lightgbm_dart, lightgbm_bagged, lightgbm_calibrated, xgboost\n  #   Ensemble:    stacking_har_lgbm, regime_blend, blend\n  #   Graph:       ghar, gnn, gnn_learned, gnnhar, dcrnn_har, stid, gsp_har', before: 4, after: 5 } },
            { text: 'Cross-validation defaults are conservative by construction: an expanding window with a 10-date [[purge-gap|purge gap]] between train and test, declared right in the config schema.',
              anchor: { file: 'workspace/configs/_CANONICAL_EXAMPLE.yaml', quote: '  purge_gap: 10        # Embargo gap in DATE units between train/test to prevent leakage', before: 4, after: 0 } },
            { text: 'The default windows are long: an initial training window of 504 trading days, two full years, with 126 day test folds, six months each.',
              anchor: { file: 'workspace/configs/_CANONICAL_EXAMPLE.yaml', quote: '  train_size: 504      # Initial training window in trading days (504 = 2 years)\n  test_size: 126       # Test window per fold in trading days (126 = 6 months)', before: 0, after: 2 } },
            C(cfg, 6, 'The tournament block also switches on the economics: delta-hedged straddle P&L, vol-targeting Sharpe, and the [[gsvivs|GSVIVS01]] signal backtest are each one toggle in the same file.'),
          ] },
          { type: 'excerpt', anchor: A(cfg, 9), caption: 'A real champion config: trial_036 trades GSVIVS01 with a tuned dead-band threshold, and the comment records exactly what the threshold bought and what would supersede it.' },
          { type: 'callout', level: 'info', title: 'CONFIGS ARE PRE-REGISTRATION',
            text: 'Trial configs carry their hypothesis and success criteria in the header comments, so the YAML is not just parameters: it is the experiment\'s pre-registration. trial_077 exists specifically to settle a champion discrepancy between two earlier trials under one shared protocol.' },
        ] },
      { id: 'data', title: 'From ticks to a number per day', kind: 'stop', minutes: 6,
        lede: 'The target of the whole project is one number per symbol per day: realized variance. This stop is how millions of ticks become that number, and why there are six different estimators of it.',
        blocks: [
          { type: 'prose', claims: [
            C(dat, 0),
            C(dat, 1, 'Alongside it comes [[bpv|bipower variation]], computed as (pi/2) times the sum of adjacent absolute return products: a jump-robust estimate of integrated variance, per Barndorff-Nielsen and Shephard 2004.'),
            C(dat, 3, 'Days with statistically significant jumps are flagged by the BNS z-test, Z = (RV - BPV) / sqrt(theta * RTQ / n), and RV is then decomposed into continuous and jump components, the raw inputs for HAR-CJ models.'),
            C(dat, 2, 'Good and bad volatility come from Patton-Sheppard [[semivariance|realized semivariances]], with the >= 0 convention chosen so RS+ plus RS- always equals RV exactly.'),
            C(dat, 5, 'For noisy tick data there is the [[rk|realized kernel]]: autocovariances weighted by a flat-top Parzen kernel, consistent under microstructure noise at the optimal convergence rate.'),
            C(dat, 12, 'The microstructure side condenses order flow into daily aggregates: [[vpin|VPIN]] over volume-time buckets, following Easley, Lopez de Prado and O\'Hara 2012.'),
            C(dat, 14, 'Causality is enforced at the data layer, not left to the models: every IV-derived feature is shifted one day so the value at t reflects only information available at close t-1.'),
            C(dat, 16, 'For the deep models, sequence_cache.py pre-stacks per-symbol 10 second bars into one padded (dates, bars, features) tensor, so training is pure GPU tensor ops with no pandas in the loop.'),
          ] },
          { type: 'excerpt', anchor: A(dat, 19), caption: 'The cache layout in one file: every raw source lands under data/raw/, every path resolved from the repo root.' },
        ] },
      { id: 'features', title: 'The feature stack', kind: 'stop', minutes: 5,
        lede: 'Layers 0 to 5, each one hypothesis about what moves tomorrow\'s volatility. A config stacks them; the registry finds them; the suffixes tell you what you are looking at.',
        blocks: [
          { type: 'prose', claims: [
            C(fea, 0),
            C(fea, 2, 'Layer 0 is the [[har|HAR]] backbone: the weekly lag is the mean of the last 5 daily RV values and the monthly lag the mean of the last 22, giving the log_rv_d, log_rv_w, log_rv_m trio every model receives.'),
            C(fea, 3, 'The HARQ extension adds sqrt realized quarticity and its interaction with RV, so a model can trust noisy RV measurements less.'),
            C(fea, 5, 'Layer 2 is where the option market enters: the [[vrp|variance risk premium]] is computed as (atm_iv/100)^2 minus rv times 252, the Carr and Wu ex-post proxy.'),
            { text: 'The code flags one family as the number one source of ML gain per a 2023 study: interactions of ATM implied vol and VIX with log RV at all three horizons.',
              anchor: { file: 'src/volforecast/features/options.py', quote: '        # --- IV × log(RV) interactions (CSV 2023: #1 ML gain source) ---', before: 2, after: 8 } },
            C(fea, 6, 'When [[zero-dte|0DTE]] implied vol is available, the layer emits an exact tenor match for one-day-ahead forecasting plus an ultra-short term slope against the 1 week tenor.'),
            C(fea, 13, 'Layer 5 encodes what is known in advance: FOMC, NFP, and OpEx proximity, all fully predictable in advance, so unlike every market-derived layer no lag shift is applied.'),
            C(fea, 14, 'The event dates are derived deterministically: NFP is the first Friday of the month and OpEx the third Friday, while the FOMC statement dates 2015 through 2026 are hardcoded as a list.'),
            C(fea, 17, 'The 73-feature gsvivs_signals layer reproduces the exact input set of the GSVIVS01 short-variance strategy, from SPX, VIX, and VX1 dynamics to put-skew and credit returns.'),
          ] },
        ] },
      { id: 'models', title: 'The model zoo', kind: 'stop', minutes: 6,
        lede: '24 registered names, one contract. The interesting design choice is not any single model: it is that the naive baselines, the champion, and the controls all take the same walk through the same folds.',
        blocks: [
          { type: 'prose', claims: [
            C(mod, 0, 'Every model self-registers under a string name via a class decorator, 24 names in all, so the pipeline instantiates any of them from configuration alone.'),
            C(mod, 2, 'All of them inherit one base contract that declares which feature layers a model needs, capability flags for tuning, progress, SHAP selection and GPU device, and joblib persistence.'),
            C(mod, 9, 'Nine naive baselines, from random walk to VIX-implied and ATM-IV-implied, share the same interface and exist to set the QLIKE floor any useful model must beat.'),
            C(mod, 5, 'LightGBM trains directly on the loss the tournament scores: a custom objective with analytic gradient 1 - exp(e) and hessian exp(e), the [[qlike-objective|QLIKE objective]] in log space.'),
            C(mod, 8, 'XGBoost is the deliberate second opinion: same objective, same six feature layers, an independent boosting library to cross-check LightGBM, and per the research journal, the current h=1 champion.'),
            C(mod, 14, 'The graph suite is engineered for honest attribution: stid runs the same harness while ignoring edges entirely, so if it matches the GNN the conclusion is that pooling plus asset identity suffices, not that spillovers matter.'),
            C(mod, 17, 'Even randomness is measured: lightgbm_bagged exists because a reseed study put the [[seed-envelope|seed envelope]] at 6.6 bps, meaning single-seed improvements under roughly 10 bps are indistinguishable from noise.'),
            C(mod, 18, 'And regimes are respected: the optimal HAR weight in a HAR plus LightGBM blend was found to be about 0.05 in calm markets but about 0.80 in high-vol regimes, so regime_blend switches weights on a volatility percentile.'),
          ] },
          { type: 'callout', level: 'broken', title: 'TWO MODELS ARE MISSING FROM THIS SNAPSHOT',
            text: 'registry.py imports models/har_family.py (the entire linear HAR family) and models/lstm.py, and both are absent, so ensure_registered() raises ImportError here. Their supporting code survives: the OLS base class, the deterministic alpha-grid tuner, and the LSTM tuning harness all read fine, which is how this page can still describe them.' },
        ] },
      { id: 'scoring', title: 'How forecasts are judged', kind: 'stop', minutes: 6,
        lede: 'The evaluation layer is unusually rigorous for a research repo. The one-sentence summary: nothing is allowed to look good by accident.',
        blocks: [
          { type: 'prose', claims: [
            C(pev, 1, 'The primary loss is [[qlike|QLIKE]] rather than RMSE because it penalizes underestimating volatility more severely than overestimating it, matching the economics: being short of realized vol is the expensive mistake.'),
            C(pev, 7, 'The cross-validation module bans random k-fold outright, calling it catastrophic look-ahead bias, and supplies purged, blocked, expanding, rolling, and panel-aware splitters instead.'),
            C(pev, 9, 'The panel splitter divides on unique dates rather than rows, so every symbol observed on a date lands in the same fold and no model trains on Tuesday for one symbol while being tested on Tuesday for another.'),
            C(pev, 3, 'Because models predict log RV, converting back to levels uses the [[duan|Duan retransformation]]: exp of an unbiased log forecast is biased low, so predictions are scaled by the mean of exponentiated residuals.'),
            C(pev, 5, 'The conditional variant of that correction is trained strictly walk-forward: the variance model for fold k fits only on out-of-sample residuals from folds 1 through k-1.'),
            C(pev, 15, 'The [[dm|Diebold-Mariano]] implementation is panel-aware: loss differentials are averaged per date before the HAC variance so Newey-West lags never cross symbol boundaries.'),
            C(pev, 18, 'Scoring is regime-conditional too: QLIKE is split into calm and turbulent buckets by top-decile market RV dates, implementing the Zhang et al. 2025 protocol, so you can see exactly where a model earns its edge.'),
            C(tst, 19, 'And the math itself is audited: FORMULAS.md maps every mathematical function to its source paper, equation number, implementation, test, and hand-computed gold values.'),
          ] },
          { type: 'excerpt', anchor: A(pev, 0), caption: 'The loss that runs the show, in both algebraic forms.' },
        ] },
      { id: 'economics', title: 'From forecasts to money', kind: 'stop', minutes: 5,
        lede: 'A better QLIKE is not the product. The product is a tradeable signal, and this repo prices its own claims with unusual honesty: costs widen near expiry, Sharpes get deflated, and one champion got retracted.',
        blocks: [
          { type: 'prose', claims: [
            C(eco, 6, 'The realistic straddle engine models the full P&L waterfall: tenor-decayed gamma, vanna and volga leakage, maturity-varying option costs, and per-rebalance hedge costs.'),
            C(eco, 7, 'Costs are not flat: per the Doshi et al. 2025 schedule, option spreads are charged at 4.5 times base inside 6 trading days to expiry and 1.75 times inside 13.'),
            C(eco, 8, 'Discrete hedging risk is priced with the Boyle-Emanuel variance formula and added to the Sharpe denominator, so rebalancing only 26 times a day cannot be quietly ignored.'),
            C(eco, 9, 'Sharpe ratios face the [[dsr|deflated Sharpe ratio]]: the probability the observed Sharpe beats the maximum expected by chance given how many configurations were tried.'),
            C(eco, 13, 'The [[gsvivs|GSVIVS01]] backtest runs against a registry of six IV sources, from the 09:10 AllDay mark Kvar to the true-fill [[kvar|exec Kvar]], each flagged for calendar versus trading-day annualization.'),
            C(eco, 1, 'Annualization conventions are handled explicitly: exec Kvar arrives in 365-day vol points and is rescaled by sqrt(252/365), about 0.831, before it may be compared with the forecast.'),
          ] },
          { type: 'table', caption: 'Real recorded results from the research journal and trial configs, each anchored in the claims above and on the agent-layer stop.', sortable: false,
            columns: ['TRIAL', 'FINDING', 'NUMBER'],
            rows: [
              ['trial-067', 'XGBoost with QLIKE objective and har_iv_0dte init: current h=1 champion', 'QLIKE 0.1292'],
              ['trial-032', 'tenor matching: har_iv_1w vs har_iv at h=1, DM p = 0.0', '0.1403 vs 0.1500'],
              ['trial-055', 'best linear model: ridge HAR with CJ decomposition plus 0DTE IV', 'QLIKE 0.13397'],
              ['trial-036', 'LightGBM champion RETRACTED: sat below the 5-seed envelope minimum', 'was 0.1289'],
              ['GNN program', 'five graph trials landed within 1 bp of the linear baseline: honest null', 'within 1 bp'],
              ['GSVIVS01', 'walk-forward threshold study: honest Sharpe after retracting an overfit 3.29', 'Sharpe 1.83'],
            ] },
          { type: 'prose', claims: [
            C(ops, 16, 'The graph program is the culture in one line: five completed graph trials landed within 1 basis point of the linear baseline at every horizon, and the journal records that as a defensible null rather than burying it.'),
            C(cfg, 11, 'Retraction is routine, not scandal: the trial-036 champion numbers were formally withdrawn after a reseed study showed each sat below the 5-seed variance envelope minimum.'),
          ] },
        ] },
      { id: 'cp-c', title: 'Checkpoint C', kind: 'cp', minutes: 4, blocks: [
        { type: 'checkpoint', id: 'cp-c1', kind: 'single',
          prompt: 'Which loss ranks the tournament, and why that one?',
          options: ['RMSE, the standard regression loss', 'QLIKE, because it penalizes underestimating volatility more than overestimating it', 'MAE, robust to outliers', 'Sharpe ratio of the straddle backtest'],
          answer: 1,
          provenance: 'evaluation/metrics.py names QLIKE the primary metric and states the asymmetry; statistical_tests.py sorts the tournament by QLIKE ascending.',
          explanation: 'Under-predicting vol is the expensive mistake in risk terms, so the loss is asymmetric on purpose. The Sharpe comes later, as the economic check on top.' },
        { type: 'checkpoint', id: 'cp-c2', kind: 'order',
          prompt: 'Put these feature layers in ascending layer-number order.',
          options: ['<code>har_core</code> (HAR lags and quarticity)', '<code>asymmetry</code> (semivariances, jumps)', '<code>options</code> (VRP, skew, tenors)', '<code>microstructure</code> (VPIN, Kyle lambda)', '<code>cross_asset</code> (rates, FX, spillover)', '<code>calendar</code> (FOMC, NFP, OpEx)'],
          answer: [1, 2, 3, 4, 5, 6],
          provenance: 'Each file\'s first docstring line states its layer number: har.py Layer 0 through calendar.py Layer 5.',
          explanation: 'The options are listed in the correct order: HAR is the Layer 0 backbone and calendar closes the numbered spine at Layer 5.' },
        { type: 'checkpoint', id: 'cp-c3', kind: 'single',
          prompt: 'What h=1 QLIKE did the current champion record, and which model is it?',
          options: ['0.1292, XGBoost (trial-067)', '0.1289, LightGBM (trial-036)', '0.13397, ridge HAR (trial-055)', '0.1500, har_iv'],
          answer: 0,
          provenance: 'workspace/research/research-journal.md records XGBoost as the new h=1 champion at 0.1292; the trial-036 0.1289 was retracted after the reseed study.',
          explanation: 'The retired number is the trap: 0.1289 looks better but sat below the seed-variance envelope, so it was withdrawn. The standing champion is XGBoost at 0.1292.' },
        { type: 'checkpoint', id: 'cp-c4', kind: 'single',
          prompt: 'Why does this repo ban random k-fold cross-validation?',
          options: ['It is slower than blocked k-fold', 'It leaks future information into training on time-series data', 'It produces unequal fold sizes', 'It cannot handle multiple symbols'],
          answer: 1,
          provenance: 'utils/cv.py: never use random k-fold on time-series data, it causes catastrophic look-ahead bias; policy/ml-constraints.md repeats the ban naming KFold(shuffle=True).',
          explanation: 'Shuffling puts future observations into training folds for earlier test periods. The ban appears twice: in the code and in agent policy, so neither a human nor a model can miss it.' },
      ] },
    ] },
    // ================================================== FOLLOW ONE PATH
    { title: 'FOLLOW ONE PATH', minutes: 14, stops: [
      { id: 'trace', title: 'One command, end to end', kind: 'stop', minutes: 10,
        lede: 'vol ingest-ohlcv, followed through 8 real hops from the shell wrapper to the parquet file it writes. Later hops ask you to predict where the call lands before showing you; that is deliberate.',
        blocks: [
          { type: 'trace', steps: [
            { claim: 'The vol shell wrapper is the front door: its ingest-ohlcv case forwards every argument to python -m volforecast ingest-ohlcv, deciding nothing itself beyond library paths.',
              next: 'main in src/volforecast/__main__.py',
              anchor: { file: 'vol', quote: '    ingest-ohlcv)\n        LD_LIBRARY_PATH="${_NIX_PY_LD_PATH}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" python -m volforecast ingest-ohlcv "$@"' } },
            { claim: 'Running the module lands in main, which builds the parser and lets argparse decide which subcommand was asked for.',
              next: '_build_parser in src/volforecast/__main__.py',
              anchor: { file: 'src/volforecast/__main__.py', quote: 'def main(argv: list[str] | None = None) -> int:\n    parser = _build_parser()' } },
            { claim: 'The parser does not define the subcommand itself: it imports the module\'s register function and hands it the subparsers object, the pattern every one of the two dozen commands follows.',
              next: 'register in src/volforecast/cli/ingest_ohlcv.py',
              predict: 'This hop ends in __main__.py. Which file does the path reach next?',
              anchor: { file: 'src/volforecast/__main__.py', quote: '    from volforecast.cli.ingest_ohlcv import register as _reg_ingest_ohlcv\n\n    _reg_ingest_ohlcv(subparsers)' } },
            { claim: 'register declares the flags: a start date defaulting to 2015-01-02, an optional end date defaulting to yesterday, a symbol filter, and force to bypass the cache.',
              next: 'handle in src/volforecast/cli/ingest_ohlcv.py',
              anchor: { file: 'src/volforecast/cli/ingest_ohlcv.py', quote: 'def register(subparsers) -> None:\n    """Register the ingest-ohlcv subcommand."""' } },
            { claim: 'set_defaults binds handle as the callable for this subcommand; handle converts the parsed strings into dates and delegates to run.',
              next: 'run in src/volforecast/cli/ingest_ohlcv.py',
              anchor: { file: 'src/volforecast/cli/ingest_ohlcv.py', quote: '    parser.set_defaults(func=handle)', after: 10 } },
            { claim: 'run is the pipeline proper: for each symbol it consults the cache, fetches daily OHLCV from TSDB when needed, and records the ingestion in the manifest.',
              next: 'save_ohlcv_cache in src/volforecast/data/ohlcv.py',
              predict: 'This hop ends in ingest_ohlcv.py. Which file does the path reach next?',
              anchor: { file: 'src/volforecast/cli/ingest_ohlcv.py', quote: '                df = fetch_ohlcv(sym, start_date, end_date)', before: 8, after: 12 } },
            { claim: 'Each fetched frame reaches save_ohlcv_cache, which writes parquet through a temporary file and an os.replace, so a crash mid-write can never leave a half-written cache.',
              next: 'ohlcv_cache_path in src/volforecast/utils/paths.py',
              predict: 'This hop ends in ohlcv.py. Which file does the path reach next?',
              anchor: { file: 'src/volforecast/data/ohlcv.py', quote: '    fd, tmp = tempfile.mkstemp(suffix=".parquet", dir=str(path.parent))', before: 3, after: 12 } },
            { claim: 'The destination is decided by ohlcv_cache_path: one parquet file per symbol under data/raw/ohlcv, the same repo-root-anchored layout every other cache uses.',
              next: null,
              anchor: { file: 'src/volforecast/utils/paths.py', quote: "def ohlcv_cache_path(symbol: str) -> Path:", after: 3, before: 6 } },
          ] },
          { type: 'callout', level: 'inferred', title: 'WHAT THIS TRACE DOES NOT PROVE',
            text: 'These hops are a static read of the source: each anchor was re-read and hash-matched, but nothing on this path was executed during generation (the TSDB fetch needs the GS network). The register / handle / run trio you just walked is the shape of every other CLI command in the repo.' },
        ] },
      { id: 'cp-d', title: 'Checkpoint D', kind: 'cp', minutes: 4, blocks: [
        { type: 'checkpoint', id: 'cp-d1', kind: 'single',
          prompt: 'The trace starts in vol and crosses 5 files. Which one does the chain end in?',
          options: ['<code>src/volforecast/data/ohlcv.py</code>', '<code>src/volforecast/__main__.py</code>', '<code>src/volforecast/cli/ingest_ohlcv.py</code>', '<code>src/volforecast/utils/paths.py</code>'],
          answer: 3,
          provenance: 'Trace hop 8 of 8: its anchor file is src/volforecast/utils/paths.py, sha256-verified like every other hop.',
          explanation: 'The chain ends where the path is decided. The other three are real hops earlier in the same trace, each where the chain would appear to end if you stopped one call too soon.' },
        { type: 'checkpoint', id: 'cp-d2', kind: 'order',
          prompt: 'Put the stages of a full vol run in the order they execute.',
          options: ['Load the YAML into an ExperimentConfig', 'Ingest gate: fetch data for universe symbols missing an RV cache', 'Tournament: train and compare all configured models', 'Update the trial registry from metrics.json'],
          answer: [1, 2, 3, 4],
          provenance: 'src/volforecast/__main__.py: from_yaml, then the missing-symbol ingest gate, then all modes route through the tournament, then update_trial_from_metrics.',
          explanation: 'Config first, data second, competition third, bookkeeping last. The options are listed in the correct order.' },
      ] },
    ] },
    // ================================================== THE AGENT LAYER
    { title: 'THE AGENT LAYER', minutes: 10, stops: [
      { id: 'agents', title: 'An operating system for agents', kind: 'stop', minutes: 7,
        lede: 'The half of the repo no codebase explainer would notice: most day-to-day work here is done by GitHub Copilot agents, and the repo is built so they cannot go off the rails.',
        blocks: [
          { type: 'stats', items: [
            { v: '48', l: 'skills', s: '8 ML vol, 40 GS infrastructure' },
            { v: '5', l: 'active personas', s: '11 more inlined and deleted' },
            { v: '15', l: 'workflows', s: 'keyword-dispatched state machines' },
            { v: '12', l: 'policy documents', s: 'non-negotiable rules' },
            { v: '50k', l: 'memory token budget', s: 'P0+P1, lint-enforced' },
            { v: '6', l: 'max concurrent subagents', s: 'hard protocol cap' },
          ] },
          { type: 'prose', claims: [
            C(aos, 1, 'The philosophy is stated outright: context bloat kills agent performance, so the orchestrating agent is a coordinator, not a laborer, decomposing non-trivial work into bounded subtasks run by subagents with fresh context.'),
            { text: 'A [[skill|skill]] is a narrow executable capability with declared authority bounds, and skills are kept honest by a size lint: a SKILL.md over 250 lines warns, over 400 errors, forcing knowledge out of skills and into memory.',
              anchor: { file: 'skills/design.md', quote: '3. `SKILL.md` must include a Skill Identity table (Name, Scope, Inputs, Outputs, Authority).', after: 0, before: 3 } },
            C(aos, 7, 'The ML discipline is encoded where agents work: the MODEL_TRAIN skill hard-codes the random k-fold ban and the log-RV training convention, the same rules the Python code enforces.'),
            { text: 'Personas carry explicit cannot-do bounds: the researcher persona is authorized for feature exploration and literature synthesis but may write no code, train no model, and touch no data pipeline.',
              anchor: { file: 'personas/INDEX.md', quote: '| [VOL-RESEARCHER](vol-researcher.md) | RV Analyst & Data Access | Feature exploration, empirical findings, QLIKE relevance, literature synthesis, data source analysis | No code, no model training, no data pipeline engineering |', before: 4, after: 0 } },
            C(aos, 18, 'The evaluation watchdog persona is read-only with Write and Edit blocked, can never approve results carrying critical issues, and its protocol-compliance stage must pass before statistical quality is even assessed.'),
            C(aos, 3, 'Memory follows [[coala|CoALA]] with hard budgets: boot loads exactly two P0 files, and total memory is capped near 60 percent of the context window, with a lint measuring actual token counts.'),
            C(ops, 3, 'Even the model is governed: every subagent is pinned to one exact model string, held in a single lint-checked constant, and any other model literal in the tracked surfaces fails the gate.'),
            C(aos, 19, 'Research itself is proceduralised: the research workflow requires a Hypothesis Card, stating the question, method, success criterion, and null hypothesis, before any data exploration begins.'),
          ] },
          { type: 'callout', level: 'info', title: 'WHY THIS MATTERS TO A NEW JOINER',
            text: 'You will not just read this repo, you will collaborate with the agents that maintain it. The contract you both answer to is AGENTS.md; the rules that bind you both are in policy/; and the same 21-check lint gate fires on your commits and theirs.' },
        ] },
      { id: 'cp-e', title: 'Checkpoint E', kind: 'cp', minutes: 3, blocks: [
        { type: 'checkpoint', id: 'cp-e1', kind: 'single',
          prompt: 'How many memory files does the agent boot protocol load at session start?',
          options: ['2', '5', '12', 'every P0 and P1 file'],
          answer: 0,
          provenance: 'AGENTS.md boot protocol: Boot = 2 P0 files (user.md and project-state.md); everything else loads on demand via INDEX.md triggers.',
          explanation: 'Two files, always; the rest is loaded per task from the index. The whole memory design exists to keep boot cheap and context lean.' },
        { type: 'checkpoint', id: 'cp-e2', kind: 'single',
          prompt: 'Which CV method does agent policy name as never acceptable on this project\'s data?',
          options: ['Expanding-window walk-forward', 'Purged k-fold with a gap', 'sklearn KFold with shuffle=True', 'Blocked k-fold'],
          answer: 2,
          provenance: 'policy/ml-constraints.md names sklearn.model_selection.KFold(shuffle=True), or any random split on time-indexed data, as never acceptable.',
          explanation: 'The same ban that lives in utils/cv.py is repeated at the policy layer with the exact API named, so an agent cannot claim ambiguity.' },
      ] },
    ] },
    // ================================================== CLOSE
    { title: 'CLOSE', minutes: 9, stops: [
      { id: 'conventions', title: 'Conventions and gotchas', kind: 'stop', minutes: 4,
        lede: 'Everything on this stop is inferred from patterns across many files. None of it is anchored to a single line, so all of it is amber: strong hints, not verified rules.',
        blocks: [
          { type: 'callout', level: 'inferred', title: 'THIS ENTIRE STOP IS UNVERIFIED',
            text: 'These are reads of the codebase, quarantined here and marked once, rather than mixed into the verified material and diluting it.' },
          { type: 'prose', claims: [
            INF('Heavy imports are deferred into function bodies, so the CLI stays responsive and a broken optional dependency only fails the command that needs it.'),
            INF('Every CLI subcommand follows the register / handle / run trio you saw in the trace; a new command is added by copying that shape into a new module.'),
            INF('Cache writes go through a temp file and an atomic replace, and ingestion merges rather than overwrites, so re-running any ingest is expected to be safe.'),
            INF('Numbers are guarded culturally as well as statistically: champions get reseed studies, thresholds get walk-forward revalidation, and the journal keeps retractions in plain sight. Treat any single-seed improvement under 10 bps as noise until bagged.'),
            INF('When you see a suffix, trust it: _d, _w, _m are daily, weekly, monthly; d_*_1d and z_* are momentum conventions; a feature ending in _0dte is an exact one-day tenor. The naming is disciplined enough to navigate by.'),
          ] },
        ] },
      { id: 'glossarystop', title: 'The glossary', kind: 'stop', minutes: 2,
        lede: 'Every dotted term on this page, in one table. Most entries link to the line of code where the concept actually lives.',
        blocks: [
          { type: 'table', caption: 'Click any dotted term in the prose to see this content in place, with a jump to the defining code.', sortable: true,
            columns: ['TERM', 'DEFINITION'],
            rows: glossary.map(g => ['<b>' + g.term + '</b>', g.def]) },
        ] },
      { id: 'audit', title: 'The ledger', kind: 'stop', minutes: 3,
        lede: 'What this page claimed, what survived verification, and what was deleted. The deleted rows are the point: a walkthrough you can trust is one that shows you its failures.',
        blocks: [
          { type: 'callout', level: 'info', title: 'HOW THIS PAGE WAS BUILT AND CHECKED',
            text: 'Authors wrote every claim with a verbatim quote, never a line number. A build script resolved each quote against the snapshot, computed the line range and a sha256 over the excerpt, and deleted claims whose quotes failed to resolve. An independent verifier then re-read every anchor from disk and re-computed every hash. Command output was captured from real runs on this machine and never edited, except that dash characters are transliterated for this artifact\'s no-dash rule.' },
          { type: 'callout', level: 'info', title: 'WHAT THIS PAGE DID NOT READ',
            text: 'Anchors resolve into the 1,063 files of this snapshot and nowhere else. The GS originals of the 14 missing modules were not available to this build; claims about them describe only what the surviving code says. The GSVIVS01 index methodology beyond this repo, and anything behind the GS network, is out of scope.' },
          { type: 'ledger' },
        ] },
      ] },
  ],
};
